DROP TABLE IF EXISTS LINK;
DROP TABLE IF EXISTS ASSET;
DROP TABLE IF EXISTS ASSOCIATION;
DROP TABLE IF EXISTS ASSOCIATION_TYPE;
DROP TABLE IF EXISTS ASSET_TYPE;
 
 
CREATE TABLE ASSET_TYPE(
                NAME VARCHAR(100) NOT NULL PRIMARY KEY,
                I18N_CREATEUSER_LABEL VARCHAR(255),
                I18N_DATECREATED_LABEL VARCHAR(255),
                I18N_DESCRIPTION_LABEL VARCHAR(255),
                I18N_ID_LABEL VARCHAR(255),
                I18N_LASTUPDATED_LABEL VARCHAR(255),
                I18N_NAME_LABEL VARCHAR(255),
                I18N_STATUS_LABEL VARCHAR(255),
                I18N_UPDATEUSER_LABEL VARCHAR(255),
                DOMAIN VARCHAR(255), 
                STATUS VARCHAR(55),
                ICON VARCHAR(255),
                ICON64 VARCHAR(4096),
                ATTRIBUTES_LABEL VARCHAR(2048),
                ATTRIBUTES_TYPE VARCHAR(2048)
);
 
 
CREATE TABLE ASSET(
                ID SERIAL PRIMARY KEY,
                ASSET_TYPE_NAME VARCHAR(100) NOT NULL,
                ASSET_TYPE_DOMAIN VARCHAR(255),
                ATTRIBUTES VARCHAR(2048),
                CREATE_USER VARCHAR(255),
                UPDATE_USER VARCHAR(255),
                DATE_CREATED TIMESTAMP,
                DESCRIPTION VARCHAR(255),
                LAST_UPDATED TIMESTAMP,
                NAME VARCHAR(255),
                STATUS VARCHAR(55),
                URL VARCHAR(255),
                ICON VARCHAR(255),
                ICON64 VARCHAR(4096),
                DOMAIN VARCHAR(255),
                VERSION INT,
                FOREIGN KEY(ASSET_TYPE_NAME) REFERENCES ASSET_TYPE(NAME)
);
 
 
CREATE TABLE ASSOCIATION_TYPE(
                NAME VARCHAR(100) NOT NULL PRIMARY KEY,
                DESCRIPTION VARCHAR(255),
		DOMAIN VARCHAR(255)
);
 
CREATE TABLE ASSOCIATION(
                SUBJECT_TYPE_NAME VARCHAR(100) NOT NULL,
                ASSOCIATION_TYPE_NAME VARCHAR(100) NOT NULL,
                OBJECT_TYPE_NAME VARCHAR(100) NOT NULL,
		DOMAIN VARCHAR(255),
    PRIMARY KEY (SUBJECT_TYPE_NAME, ASSOCIATION_TYPE_NAME, OBJECT_TYPE_NAME),
                FOREIGN KEY (SUBJECT_TYPE_NAME) REFERENCES ASSET_TYPE(NAME),
                FOREIGN KEY (OBJECT_TYPE_NAME) REFERENCES ASSET_TYPE(NAME),
                FOREIGN KEY (ASSOCIATION_TYPE_NAME) REFERENCES ASSOCIATION_TYPE(NAME)
);

CREATE TABLE LINK(
                SUBJECT_ID BIGINT UNSIGNED NOT NULL,
                ASSOCIATION_TYPE_NAME VARCHAR(100) NOT NULL,
                OBJECT_ID BIGINT UNSIGNED NOT NULL,
		DOMAIN VARCHAR(255),
                PRIMARY KEY (SUBJECT_ID, ASSOCIATION_TYPE_NAME, OBJECT_ID),
                CONSTRAINT fk1 FOREIGN KEY (SUBJECT_ID) REFERENCES ASSET(ID),
                CONSTRAINT fk2 FOREIGN KEY (OBJECT_ID) REFERENCES ASSET(ID),
                CONSTRAINT fk3 FOREIGN KEY (ASSOCIATION_TYPE_NAME) REFERENCES ASSOCIATION_TYPE(NAME)
);
 
INSERT INTO ASSET_TYPE (
  NAME, DOMAIN, I18N_CREATEUSER_LABEL, I18N_DATECREATED_LABEL, I18N_DESCRIPTION_LABEL,
  I18N_ID_LABEL, I18N_LASTUPDATED_LABEL, I18N_NAME_LABEL, I18N_STATUS_LABEL,
  I18N_UPDATEUSER_LABEL, ICON, ICON64, ATTRIBUTES_LABEL, ATTRIBUTES_TYPE
) VALUES (
  'Role', 'system', 'creator', 'created_date', 'description', 'id', 'last_update',
  'name', 'status', 'updater', '', '', '{}', '{}'
); 

INSERT INTO ASSET_TYPE (
  NAME, DOMAIN, I18N_CREATEUSER_LABEL, I18N_DATECREATED_LABEL, I18N_DESCRIPTION_LABEL,
  I18N_ID_LABEL, I18N_LASTUPDATED_LABEL, I18N_NAME_LABEL, I18N_STATUS_LABEL,
  I18N_UPDATEUSER_LABEL, ICON, ICON64, ATTRIBUTES_LABEL, ATTRIBUTES_TYPE
) VALUES (
  'User', 'system', 'creator', 'created_date', 'description', 'id', 'last_update',
  'name', 'status', 'updater', '', '', '{"password":"password", "email":"email"}',
  '{"password":"password", "email":"email"}'
);
 

INSERT INTO ASSET_TYPE (
  NAME, DOMAIN, I18N_CREATEUSER_LABEL, I18N_DATECREATED_LABEL, I18N_DESCRIPTION_LABEL,
  I18N_ID_LABEL, I18N_LASTUPDATED_LABEL, I18N_NAME_LABEL, I18N_STATUS_LABEL,
  I18N_UPDATEUSER_LABEL, ICON, ICON64, ATTRIBUTES_LABEL, ATTRIBUTES_TYPE
) VALUES (
  'Domain', 'system', 'creator', 'created_date', 'description', 'id', 'last_update',
  'name', 'status', 'updater', '', '', '{}','{}'
);
 
INSERT INTO ASSET (ASSET_TYPE_NAME,ATTRIBUTES,CREATE_USER,UPDATE_USER,DATE_CREATED,DESCRIPTION,LAST_UPDATED,NAME,STATUS,URL,VERSION) VALUES ('User','{"password":"1000:5b42403738353265393232:ab89b0c65354d57bdcf9659a53d410fa0a8b7d0f9dee270f1e9f51d87d1a9d06bfb5d1e114566b34c6e658f6d4d7d816b90a2841a5e93e7604ee5d52963a9135", "email":"mackleaps@mackenzie.br"}',null,null, CURRENT_TIMESTAMP,'Usuario Mackleaps', CURRENT_TIMESTAMP,'mackleaps','created',null,1);


INSERT INTO ASSET (ASSET_TYPE_NAME,ATTRIBUTES,CREATE_USER,UPDATE_USER,DATE_CREATED,DESCRIPTION,LAST_UPDATED,NAME,STATUS,URL,VERSION) VALUES ('Role',null,null,null,CURRENT_TIMESTAMP,'Superuser do sistema',CURRENT_TIMESTAMP,'Superuser','created',null,1);
 
INSERT INTO ASSOCIATION_TYPE (NAME,DESCRIPTION) VALUES ('Has role','Subject has role of object');
INSERT INTO LINK (SUBJECT_ID,ASSOCIATION_TYPE_NAME,OBJECT_ID) VALUES ((select ASSET.ID from ASSET where ASSET.NAME='mackleaps' and ASSET.ASSET_TYPE_NAME='User'),'Has role',(select ASSET.ID from ASSET where ASSET.NAME='Superuser' and ASSET.ASSET_TYPE_NAME='Role'));
