# spring.application.name=AssetAPI
# db.url=http://172.16.50.199:8089
# db.token=mytoken
# db.user=mackleaps
# server.port=8090


spring.application.name=AssetAPI
db.url=http://assetApidb:3306
db.token=mytoken
db.user=mackleaps
server.port=8090